services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB-PORT = 3306
      - DB_USER=root
      - DB_PASS=262121hnrA_SQL
      - DB_NAME=notedb
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 262121hnrA_SQL
      MYSQL_DATABASE: notedb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
